[package]
name = "plinth"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.4"
euclid = "0.22"
smallvec = "1"
tracing = "0.1"
tracing-subscriber = "0.3"

[dependencies.windows]
version = "0.48"
features = [
    "Win32_Foundation",
    "Win32_Graphics_DirectComposition",
    "Win32_Graphics_Direct3D12",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Direct3D_Fxc",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Gdi",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Security",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading"
]
